name: linux_build_client
run-name: ${{ github.actor}} is build the linux mastodon client
on:
  push:
    branches:
      - main
      - installer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Upload DEB package
        uses: actions/upload-artifact@v3
        with:
          name: Installer files
          path: target/