name: Mac Client

on:
  push:
    branches:
      - maina
    tags:
      - sprint*

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B install -DskipTests --file pom.xml
      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: DMG file
          path: target/installer/*.dmg
      - name: Upload PKG
        uses: actions/upload-artifact@v3
        with:
          name: PKG file
          path: target/installer/*.pkg